// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: account.sql

package db

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    owner,
    balance,
    currency
) VALUES (
    $1,$2, $3
) RETURNING id, owner, balance, currency, created_at
`

func (q *Queries) CreateAccount(ctx context.Context, owner string, balance int64, currency string) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount, owner, balance, currency)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}
